# atril
# Autogenerated from man page /usr/share/man/man1/atril.1.gz
complete -c atril -s p -l page-label -d 'Here you can specify a page label, this page will be selected in the document…'
complete -c atril -s i -l page-index -d 'Here you can specify a page number, this page will be selected in the documen…'
complete -c atril -s f -l fullscreen -d 'Start atril in fullscreen mode'
complete -c atril -s s -l presentation -d 'Start atril in presentation mode'
complete -c atril -s w -l preview -d 'Start atril in preview mode'
complete -c atril -l display -d 'X display to use'
complete -c atril -l version -d 'Output version information and exit'
complete -c atril -s '?' -s h -l help -d 'Print standard command line options'

