# budgie-screensaver
# Autogenerated from man page /usr/share/man/man1/budgie-screensaver.1.gz
complete -c budgie-screensaver -l no-daemon -d 'Don\'t become a daemon'
complete -c budgie-screensaver -l debug -d 'Enable debugging code'

