# budgie-screensaver-command
# Autogenerated from man page /usr/share/man/man1/budgie-screensaver-command.1.gz
complete -c budgie-screensaver-command -l exit -d 'Causes the screensaver to exit gracefully'
complete -c budgie-screensaver-command -s q -l query -d 'Query the state of the screensaver'
complete -c budgie-screensaver-command -s t -l time -d 'Query the length of time the screensaver has been active'
complete -c budgie-screensaver-command -s l -l lock -d 'Tells the running screensaver process to lock the screen immediately'
complete -c budgie-screensaver-command -s a -l activate -d 'Turn the screensaver on (blank the screen)'
complete -c budgie-screensaver-command -s d -l deactivate -d 'If the screensaver is active then deactivate it (un-blank the screen)'
complete -c budgie-screensaver-command -s V -l version -d 'Version of this application SEE ALSO budgie-screensaver (1)'

