# caja
# Autogenerated from man page /usr/share/man/man1/caja.1.gz
complete -c caja -l browser -d 'Open a browser window'
complete -c caja -s c -l check -d 'Perform a quick set of self-check tests'
complete -c caja -l display -d 'X display to use'
complete -c caja -s g -l geometry -d 'Create the initial window with the given geometry'
complete -c caja -s t -l tabs -d 'Open URIs in tabs'
complete -c caja -s n -l no-default-window -d 'Only create windows for explicitly specified URIs'
complete -c caja -l no-desktop -d 'Do not manage the desktop (ignore the preference set in the preferences dialo…'
complete -c caja -l force-desktop -d 'Manage the desktop regardless of set preferences or environment (on new start…'
complete -c caja -s q -l quit -d 'Quit Caja'
complete -c caja -l version -d 'Print current version information and exit'
complete -c caja -s '?' -s h -l help -d 'Print standard command line options'

