# caja-connect-server
# Autogenerated from man page /usr/share/man/man1/caja-connect-server.1.gz
complete -c caja-connect-server -l display -d 'X display to use'
complete -c caja-connect-server -s '?' -s h -l help -d 'Print standard command line options'

