# engrampa
# Autogenerated from man page /usr/share/man/man1/engrampa.1.gz
complete -c engrampa -s a -l add-to -d 'Add files to the specified archive and quit the program'
complete -c engrampa -s d -l add -d 'Add files asking the name of the archive and quit the program'
complete -c engrampa -s e -l extract-to -d 'Extract archives to the specified folder and quit the program'
complete -c engrampa -s f -l extract -d 'Extract archives asking the destination folder and quit the program'
complete -c engrampa -s h -l extract-here -d 'Extract archives using the archive name as destination folder and quit the pr…'
complete -c engrampa -l default-dir -d 'Default folder to use for the \'--add\' and \'--extract\' commands'
complete -c engrampa -l force -d 'Create destination folder without asking confirmation'
complete -c engrampa -l display -d 'X display to use'
complete -c engrampa -s '?' -l help -d 'Print standard command line options'
complete -c engrampa -l help-all -d 'Print all command line options'

