# eom
# Autogenerated from man page /usr/share/man/man1/eom.1.gz
complete -c eom -l display -d 'X display to use'
complete -c eom -s f -l fullscreen -d 'Start eom in fullscreen mode'
complete -c eom -s c -l disable-image-collection -d 'Disable image collection viewer'
complete -c eom -s s -l slide-show -d 'Open in slideshow mode'
complete -c eom -s n -l new-instance -d 'Start a new instance instead of reusing an existing window'
complete -c eom -l version -d 'Output version information and exit'
complete -c eom -s h -l help -d 'Print standard command line options'

