# marco
# Autogenerated from man page /usr/share/man/man1/marco.1.gz
complete -c marco -s d -l display -d 'X display to use'
complete -c marco -l sync -d 'br Make X calls synchronous'
complete -c marco -l replace -d 'Replace the currently running window manager with Marco'
complete -c marco -l sm-disable -d 'Disable the connection to the session manager'
complete -c marco -l sm-client-id -d 'Specify a session management ID'
complete -c marco -l sm-save-file -d 'Restore from a session management savefile'
complete -c marco -s c -l composite -d 'Turn compositing ON'
complete -c marco -l no-composite -d 'Turn compositing OFF'
complete -c marco -l no-force-fullscreen -d 'Do not create fullscreen windows without decorations'
complete -c marco -l version -d 'Print current version information and exit'

