# mate-session-inhibit
# Autogenerated from man page /usr/share/man/man1/mate-session-inhibit.1.gz
complete -c mate-session-inhibit -s h -l help -d 'print help and exit'
complete -c mate-session-inhibit -l version -d 'print version information and exit'
complete -c mate-session-inhibit -l app-id -d 'The application id to use when calling the mate-session Inhibit() method'
complete -c mate-session-inhibit -l reason -d 'A human-readable reason to pass along when calling the mate-session Inhibit()…'
complete -c mate-session-inhibit -l inhibit -d 'ARG specifies the things to inhibit, as a colon-separated list'

