# mate-settings-daemon
# Autogenerated from man page /usr/share/man/man1/mate-settings-daemon.1.gz
complete -c mate-settings-daemon -s '?' -l help -d 'Show this help message . PP Application options'
complete -c mate-settings-daemon -l debug -d 'Enable debugging code'
complete -c mate-settings-daemon -l replace -d 'Replaces the current running daemon'
complete -c mate-settings-daemon -l display -d 'X display to use'

