# mate-power-backlight-helper
# Autogenerated from man page /usr/share/man/man1/mate-power-backlight-helper.1.gz
complete -c mate-power-backlight-helper -l help -d 'Show summary of options'
complete -c mate-power-backlight-helper -l set-brightness -d 'Set the given brightness'
complete -c mate-power-backlight-helper -l get-brightness -d 'Get the current brightness'

