# mate-charpick-applet
# Autogenerated from man page /usr/share/man/man1/mate-charpick-applet.1.gz
complete -c mate-charpick-applet -l activate-goad-server -d '(Internal use only) GOAD server ID to activate'

