# mate-volume-control
# Autogenerated from man page /usr/share/man/man1/mate-volume-control.1.gz
complete -c mate-volume-control -s b -l backend -d 'Launch mate-volume-control with the selected sound system backend'
complete -c mate-volume-control -s d -l debug -d 'Enable debugging code'
complete -c mate-volume-control -s p -l page -d 'Launch mate-volume-control on the specified page/tab'
complete -c mate-volume-control -s v -l version -d 'Output version information and exit'
complete -c mate-volume-control -l display -d 'X display to use'
complete -c mate-volume-control -s '?' -s h -l help -d 'Print standard command line options'
complete -c mate-volume-control -l help-all -d 'Print all command line options'
complete -c mate-volume-control -l help-gtk -d 'Print GTK+ options'

