# mate-session-save
# Autogenerated from man page /usr/share/man/man1/mate-session-save.1.gz
complete -c mate-session-save -l logout -d 'Log out'
complete -c mate-session-save -l force-logout -d 'Log out, ignoring any existing inhibitors'
complete -c mate-session-save -l logout-dialog -d 'Show logout dialog'
complete -c mate-session-save -l shutdown-dialog -d 'Show shutdown dialog'
complete -c mate-session-save -l gui -d 'br Use dialog boxes for errors'
complete -c mate-session-save -l display -d 'X display to use'
complete -c mate-session-save -l version -d 'Output version information and exit'
complete -c mate-session-save -s '?' -s h -l help -d 'Print standard command line options'

