# mate-multiload-applet
# Autogenerated from man page /usr/share/man/man1/mate-multiload-applet.1.gz
complete -c mate-multiload-applet -l activate-goad-server -d '(Internal use only) GOAD server ID to activate'

