# mate-control-center
# Autogenerated from man page /usr/share/man/man1/mate-control-center.1.gz
complete -c mate-control-center -s '?' -l help -d 'Print the application\'s help options and exit'
complete -c mate-control-center -l help-gtk -d 'Print GTK help options and exit'
complete -c mate-control-center -l help-all -d 'Print application and GTK help options and exit'
complete -c mate-control-center -l hide -d 'Hide on start (useful for preloading the shell)'

