# mate-calc
# Autogenerated from man page /usr/share/man/man1/mate-calc.1.gz
complete -c mate-calc -s s -l solve -d 'Solve the equation provided following this option'
complete -c mate-calc -l version -d 'Output version information and exit'
complete -c mate-calc -s h -s '?' -l help -d 'Print standard command line options'

