# mate-dictionary
# Autogenerated from man page /usr/share/man/man1/mate-dictionary.1.gz
complete -c mate-dictionary -l look-up -d 'Looks up the specified word using the pre-defined dictionary source'
complete -c mate-dictionary -l match -d 'Matches one or more words using the pre-defined dictionary source'
complete -c mate-dictionary -s s -l source -d 'Uses the specified source for looking up words'
complete -c mate-dictionary -s n -l no-window -d 'Using this switch with the --look-up will print the definitions found on the …'
complete -c mate-dictionary -s D -l database -d 'Use the specified database for looking up words'
complete -c mate-dictionary -l help -d 'Display help information'

