# mate-drivemount-applet
# Autogenerated from man page /usr/share/man/man1/mate-drivemount-applet.1.gz
complete -c mate-drivemount-applet -l activate-goad-server -d '(Internal use only) GOAD server ID to activate'

