# mate-geyes-applet
# Autogenerated from man page /usr/share/man/man1/mate-geyes-applet.1.gz
complete -c mate-geyes-applet -l activate-goad-server -d '(Internal use only) GOAD server ID to activate'

