# mate-thumbnail-font
# Autogenerated from man page /usr/share/man/man1/mate-thumbnail-font.1.gz
complete -c mate-thumbnail-font -s h -l help -d 'Show some help text'
complete -c mate-thumbnail-font -s t -l text -d 'Text to thumbnail (default: Aa)'
complete -c mate-thumbnail-font -s s -l size -d 'Font size (default: 64)'

