# mate-session-properties
# Autogenerated from man page /usr/share/man/man1/mate-session-properties.1.gz
complete -c mate-session-properties -l display -d 'X display to use'
complete -c mate-session-properties -l version -d 'Output version information and exit'
complete -c mate-session-properties -s '?' -s h -l help -d 'Print standard command line options'

