# mate-session
# Autogenerated from man page /usr/share/man/man1/mate-session.1.gz
complete -c mate-session -s a -l autostart -d 'Start all applications defined in "DIR", instead of starting the applications…'
complete -c mate-session -s f -l failsafe -d 'Run in fail-safe mode.  User-specified applications will not be started'
complete -c mate-session -l debug -d 'Enable debugging code'
complete -c mate-session -l display -d 'X display to use'
complete -c mate-session -l version -d 'Output version information and exit'
complete -c mate-session -s '?' -s h -l help -d 'Print standard command line options'

