# mate-cpufreq-selector
# Autogenerated from man page /usr/share/man/man1/mate-cpufreq-selector.1.gz
complete -c mate-cpufreq-selector -s c -l cpu -d 'Specify the CPU Number to adjust settings for'
complete -c mate-cpufreq-selector -s g -l governor -d 'Specify a valid CPU Governor to use.  (ie'
complete -c mate-cpufreq-selector -s f -l frequency -d 'Specify a CPU Frequency to set in KHz'

