# mate-screenshot
# Autogenerated from man page /usr/share/man/man1/mate-screenshot.1.gz
complete -c mate-screenshot -s w -l window -d 'Grab the current active window instead of the entire screen'
complete -c mate-screenshot -s a -l area -d 'Grab an area of the screen instead of the entire screen'
complete -c mate-screenshot -s b -l include-border -d 'Include the window border within the screenshot'
complete -c mate-screenshot -s B -l remove-border -d 'Remove the window border from the screenshot'
complete -c mate-screenshot -s d -l delay -d 'Take the screenshot after the specified delay [in seconds]'
complete -c mate-screenshot -s e -l effect -d 'Add an effect to the outside of the screenshot border'
complete -c mate-screenshot -s i -l interactive -d 'Interactively set options in a dialog'
complete -c mate-screenshot -l display -d 'X display to use'

