# mate-volume-control-status-icon
# Autogenerated from man page /usr/share/man/man1/mate-volume-control-status-icon.1.gz
complete -c mate-volume-control-status-icon -s v -l version -d 'Output version information and exit'
complete -c mate-volume-control-status-icon -s d -l debug -d 'Enable debugging code'
complete -c mate-volume-control-status-icon -l display -d 'X display to use'
complete -c mate-volume-control-status-icon -s '?' -s h -l help -d 'Print standard command line options'
complete -c mate-volume-control-status-icon -l help-all -d 'Print all command line options'
complete -c mate-volume-control-status-icon -l help-gtk -d 'Print GTK+ options'

