# mate-screensaver
# Autogenerated from man page /usr/share/man/man1/mate-screensaver.1.gz
complete -c mate-screensaver -l display -d 'X display to use'
complete -c mate-screensaver -l no-daemon -d 'Don\'t start as a daemon'
complete -c mate-screensaver -l debug -d 'Enable debugging messages for mate-screensaver'
complete -c mate-screensaver -l version -d 'Output version information and exit'
complete -c mate-screensaver -s h -l help -d 'Print standard command line options'

