# oggdec
# Autogenerated from man page /usr/share/man/man1/oggdec.1.gz
complete -c oggdec -s Q -l quiet -d 'Suppresses program output'
complete -c oggdec -s h -l help -d 'Print help message'
complete -c oggdec -s V -l version -d 'Display version information'
complete -c oggdec -s b -l bits -d 'Bits per sample.   Valid values are 8 or 16'
complete -c oggdec -s e -l endian -d 'Set endianness for 16-bit output'
complete -c oggdec -s R -l raw -d 'Output in raw format.   If not specified, writes Wave file (RIFF headers)'
complete -c oggdec -s s -l sign -d 'Set signedness for output.   0 for unsigned, 1 (default) for signed'

