# ogginfo
# Autogenerated from man page /usr/share/man/man1/ogginfo.1.gz
complete -c ogginfo -s h -d 'Show a help and usage message'
complete -c ogginfo -s q -d 'Quiet mode.  This may be specified multiple times'
complete -c ogginfo -s v -d 'Verbose mode.  At the current time, this does not do anything'

