# pluma
# Autogenerated from man page /usr/share/man/man1/pluma.1.gz
complete -c pluma -l display -d 'X display to use'
complete -c pluma -l encoding -d 'Set the character encoding to be used for opening the files listed on the com…'
complete -c pluma -l new-window -d 'Create a new toplevel window in an existing instance of pluma'
complete -c pluma -l new-document -d 'Create a new document in an existing instance of pluma, on the last Pluma win…'
complete -c pluma -l list-encodings -d 'Display list of possible values for the encoding option and exit'
complete -c pluma -l version -d 'Output version information and exit'
complete -c pluma -s '?' -s h -l help -d 'Print standard command line options'

