# vorbiscomment
# Autogenerated from man page /usr/share/man/man1/vorbiscomment.1.gz
complete -c vorbiscomment -s a -l append -d 'Updates comments'
complete -c vorbiscomment -s c -l commentfile -d 'Take comments from a file'
complete -c vorbiscomment -s h -l help -d 'Show command help'
complete -c vorbiscomment -s l -l list -d 'List the comments in the Ogg Vorbis file'
complete -c vorbiscomment -s q -l quiet -d 'Quiet mode.   No messages are displayed'
complete -c vorbiscomment -s t -l tag -d 'Specify a new tag on the command line.  Each tag is given as a single string'
complete -c vorbiscomment -s d -l rm -d 'Specify a tag on the command line for removal'
complete -c vorbiscomment -s w -l write -d 'Replace comments with the new set given either on the command line with -t or…'
complete -c vorbiscomment -s R -l raw -d 'Read and write comments in UTF-8, rather than converting to the user\'s charac…'
complete -c vorbiscomment -s e -l escapes -d 'Quote/unquote newlines and backslashes in the comments'
complete -c vorbiscomment -s V -l version -d 'Display the version of vorbiscomment.  EXAMPLES'

