# zeitgeist-daemon
# Autogenerated from man page /usr/share/man/man1/zeitgeist-daemon.1.gz
complete -c zeitgeist-daemon -l no-datahub -d 'Do not start zeitgeist-datahub together with this daemon'
complete -c zeitgeist-daemon -s r -l replace -d 'Replace any existing Zeitgeist instance if there is one already running'
complete -c zeitgeist-daemon -l log-level -d 'Specifies how much information should be printed to the standard output'
complete -c zeitgeist-daemon -l log-file -d 'Specifies a file to which log output will be appended'
complete -c zeitgeist-daemon -s q -l quit -d 'Stop a currently running Zeitgeist instance and exit'
complete -c zeitgeist-daemon -s v -l version -d 'Shows which version of Zeitgeist is being executed'
complete -c zeitgeist-daemon -s h -l help -d 'Shows a short help message listing all supported options'

